name: Build
on:
  pull_request:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    env:
      PKGFORGE_STATEFILE: /tmp/pkgforge
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install AWS CLI
      run: pip install --user awscli
    - name: Build
      run: make
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        BUCKET: akerl-githubauthlambda
      run: aws s3 cp pkg/payload.zip "s3://$BUCKET/$GITHUB_REF_NAME.zip"
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      run: make release
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Post to hook-exporter
      run: ./.github/exporter.sh
      env:
        EXPORTER_TOKEN: ${{ secrets.EXPORTER_TOKEN }}
        JOB_STATUS: ${{ job.status }}
      if: ${{ always() }}
